module Grammars
using HerbGrammar
grammar_11604909 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "."
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_12948338 = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = "_"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_17212077 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "/"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_19274448 = @cfgrammar begin
	Start = ntBool
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "9999999"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_19558979 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_2
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 0
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = 4
	ntInt = 5
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_2171308 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_23435880 = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_25239569 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "BRD"
	ntString = "DRS"
	ntString = "LDS"
	ntString = "Branding"
	ntString = "Direct Response"
	ntString = "Leads"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_28627624_1 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "="
	ntString = "-"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_30732554 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "|"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_31753108 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = 4
	ntInt = 5
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_33619752 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "Inc"
	ntString = "Company"
	ntString = "Corporation"
	ntString = "Enterprises"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_34801680 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "Name"
	ntString = "="
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_35016216 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = "C0"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_35744094 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "/"
	ntString = "microsoft"
	ntString = "windows"
	ntString = "apple"
	ntString = "mac"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_36462127 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "/"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_37281007 = @cfgrammar begin
	Start = ntBool
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_37534494 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = _arg_3
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_38664547 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "that"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_38871714 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "<"
	ntString = ">"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_39060015 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "/"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_40498040 = @cfgrammar begin
	Start = ntBool
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "overhead"
	ntString = "some project"
	ntString = "other"
	ntString = "boo"
	ntString = ","
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_41503046 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "ssp."
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_43120683 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "1"
	ntString = "2"
	ntString = "3"
	ntString = "4"
	ntString = "apple"
	ntString = "bananas"
	ntString = "strawberries"
	ntString = "oranges"
	ntString = ","
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_43606446 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = ">"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_44789427 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "-"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_2
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_add_a_line_break_with_a_formula = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = _arg_3
	ntString = ""
	ntString = " "
	ntString = "/n"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_cell_contains_all_of_many_things = @cfgrammar begin
	Start = ntBool
	ntString = _arg_1
	ntString = _arg_2
	ntString = _arg_3
	ntString = _arg_4
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_cell_contains_number = @cfgrammar begin
	Start = ntBool
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "1"
	ntString = "2"
	ntString = "3"
	ntString = "4"
	ntString = "5"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_cell_contains_one_of_many_things = @cfgrammar begin
	Start = ntBool
	ntString = _arg_1
	ntString = _arg_2
	ntString = _arg_3
	ntString = _arg_4
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_cell_contains_one_of_many_with_exclusions = @cfgrammar begin
	Start = ntBool
	ntString = _arg_1
	ntString = _arg_2
	ntString = _arg_3
	ntString = _arg_4
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_cell_contains_some_words_but_not_others = @cfgrammar begin
	Start = ntBool
	ntString = _arg_1
	ntString = _arg_2
	ntString = _arg_3
	ntString = _arg_4
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_cell_contains_specific_text = @cfgrammar begin
	Start = ntBool
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_cell_equals_one_of_many_things = @cfgrammar begin
	Start = ntBool
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "yellow"
	ntString = "orange"
	ntString = "green"
	ntString = "blue"
	ntString = "pink"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_change_negative_numbers_to_positive = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "-"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_clean_and_reformat_telephone_numbers = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = ","
	ntString = "-"
	ntString = "."
	ntString = "<"
	ntString = ">"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_compare_two_strings = @cfgrammar begin
	Start = ntBool
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_convert_numbers_to_text = @cfgrammar begin
	Start = ntString
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_1
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_convert_text_to_numbers = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_count_consecutive_monthly_orders = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "0"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_count_line_breaks_in_cell = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "/n"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 0
	ntInt = 1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_count_specific_characters_in_a_cell = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_count_specific_words_in_a_cell = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_count_total_characters_in_a_cell = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_count_total_words_in_a_cell = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_create_email_address_from_name = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = "_acme.com"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_create_email_address_with_name_and_domain = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = _arg_3
	ntString = ""
	ntString = " "
	ntString = "_"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_exceljet1 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = "_"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_exceljet2 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "."
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_exceljet3 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "="
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_exceljet4 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "="
	ntString = "/"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_extract_nth_word_from_text_string = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_2
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_extract_text_between_parentheses = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "<"
	ntString = ">"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_extract_word_containing_specific_text = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "_"
	ntString = "."
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = 4
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_extract_word_that_begins_with_specific_character = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "_"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_find_nth_occurrence_of_character = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "_"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_2
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_get_domain_from_email_address_2 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = "_"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_get_domain_name_from_url = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "/"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_get_first_name_from_name_with_comma = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = ","
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_2
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_get_first_name_from_name = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_get_first_word = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_get_last_line_in_cell = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "/n"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_get_last_name_from_name_with_comma = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = ","
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_get_last_name_from_name = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_get_last_word = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_get_middle_name_from_full_name = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_join_cells_with_comma = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = _arg_3
	ntString = ""
	ntString = " "
	ntString = ","
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_join_first_and_last_name = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_most_frequently_occurring_text = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = _arg_3
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_phone_5_short = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = " "
	ntString = "+"
	ntString = "-"
	ntString = "."
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 0
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = 4
	ntInt = 5
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_phone_6_short = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = " "
	ntString = "+"
	ntString = "-"
	ntString = "."
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 0
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = 4
	ntInt = 5
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_phone_7_short = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = " "
	ntString = "+"
	ntString = "-"
	ntString = "."
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 0
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = 4
	ntInt = 5
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_phone_9_short = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = " "
	ntString = "+"
	ntString = "-"
	ntString = "."
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 0
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = 4
	ntInt = 5
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_position_of_2nd_3rd_etc_instance_of_character = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_3
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_remove_characters_from_left = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_2
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_remove_characters_from_right = @cfgrammar begin
	Start = ntInt
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_remove_file_extension_from_filename = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "."
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_remove_leading_and_trailing_spaces_from_text = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_remove_text_by_matching = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "-"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_remove_text_by_position = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "/"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_remove_unwanted_characters = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_replace_one_character_with_another = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "-"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_split_numbers_from_units_of_measure_1 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_2
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_split_numbers_from_units_of_measure_2 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_2
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_split_text_and_numbers = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_2
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_split_text_string_at_specific_character = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "_"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = _arg_2
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_stackoverflow1 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "Inc"
	ntString = "."
	ntString = ","
	ntString = "LLC"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_stackoverflow10 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = 4
	ntInt = 5
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_stackoverflow11 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "_"
	ntString = "1"
	ntString = "2"
	ntString = "3"
	ntString = "4"
	ntString = "5"
	ntString = "6"
	ntString = "7"
	ntString = "8"
	ntString = "9"
	ntString = "0"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_stackoverflow2 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "in"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_stackoverflow3 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "1"
	ntString = "9"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_stackoverflow4 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "<"
	ntString = ">"
	ntString = ","
	ntString = "/"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_stackoverflow5 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "0"
	ntString = "1"
	ntString = "4"
	ntString = "5"
	ntString = "9"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_stackoverflow6 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "="
	ntString = "-"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_stackoverflow7 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = _arg_2
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_stackoverflow8 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "/"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 2
	ntInt = 3
	ntInt = 4
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_stackoverflow9 = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_strip_html_from_text_or_numbers = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "<"
	ntString = ">"
	ntString = "b"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_strip_non_numeric_characters = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = "%"
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = 4
	ntInt = 5
	ntInt = 6
	ntInt = 7
	ntInt = 8
	ntInt = 9
	ntInt = 0
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
grammar_strip_numeric_characters_from_cell = @cfgrammar begin
	Start = ntString
	ntString = _arg_1
	ntString = ""
	ntString = " "
	ntString = concat_cvc(ntString, ntString)
	ntString = replace_cvc(ntString, ntString, ntString)
	ntString = at_cvc(ntString, ntInt)
	ntString = int_to_str_cvc(ntInt)
	ntString = ntBool ? ntString : ntString
	ntString = substr_cvc(ntString, ntInt, ntInt)
	ntInt = 1
	ntInt = 0
	ntInt = -1
	ntInt = 1
	ntInt = 2
	ntInt = 3
	ntInt = 4
	ntInt = 5
	ntInt = 6
	ntInt = 7
	ntInt = 8
	ntInt = 9
	ntInt = 0
	ntInt = ntInt + ntInt
	ntInt = ntInt - ntInt
	ntInt = len_cvc(ntString)
	ntInt = str_to_int_cvc(ntString)
	ntInt = ntBool ? ntInt : ntInt
	ntInt = indexof_cvc(ntString, ntString, ntInt)
	ntBool = true
	ntBool = false
	ntBool = ntInt == ntInt
	ntBool = prefixof_cvc(ntString, ntString)
	ntBool = suffixof_cvc(ntString, ntString)
	ntBool = contains_cvc(ntString, ntString)
end
end